language: csharp
mono: latest
solution: receiptparser-net46.sln

install:
 - mono .paket/paket.bootstrapper.exe
 - mono .paket/paket.exe restore
 - mono nuget install NUnit.Console -Version 3.5.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Debug receiptparser-net46.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe -v ReceiptParser.Test/bin/Debug/ReceiptParser.Test.dll